// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfpG81qF5aav7BXIxHC7GcMGoR6UNGNPA',
    appId: '1:222998616932:web:df46281df24174af88b871',
    messagingSenderId: '222998616932',
    projectId: 'conexusit-test',
    authDomain: 'conexusit-test.firebaseapp.com',
    storageBucket: 'conexusit-test.appspot.com',
    measurementId: 'G-LC45B5G62V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg6GgV6QclldCl3ZBb56ld2csT3lGpPCY',
    appId: '1:222998616932:android:69535248d05e073488b871',
    messagingSenderId: '222998616932',
    projectId: 'conexusit-test',
    storageBucket: 'conexusit-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7oKaBO4G-d6mtUWgrGmSsNB_Y6jlJbaw',
    appId: '1:222998616932:ios:d9c5bf4924d932ee88b871',
    messagingSenderId: '222998616932',
    projectId: 'conexusit-test',
    storageBucket: 'conexusit-test.appspot.com',
    iosClientId: '222998616932-jka5mtb662976l6t2jbhct54blcirvf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.conexusForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7oKaBO4G-d6mtUWgrGmSsNB_Y6jlJbaw',
    appId: '1:222998616932:ios:d9c5bf4924d932ee88b871',
    messagingSenderId: '222998616932',
    projectId: 'conexusit-test',
    storageBucket: 'conexusit-test.appspot.com',
    iosClientId: '222998616932-jka5mtb662976l6t2jbhct54blcirvf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.conexusForm',
  );
}
